"""
MATS Orchestrator - Agent Output Schemas

Defines expected output structures from team lead agents.
"""
from typing import Dict, Any, List, Optional
from pydantic import BaseModel, Field, validator


class SREOutput(BaseModel):
    """Expected output schema from SRE Agent"""
    status: str = Field(..., description="SUCCESS|PARTIAL|FAILURE|WAITING_FOR_APPROVAL")
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Confidence in findings")
    
    evidence: Dict[str, Any] = Field(default_factory=dict, description="Collected evidence")
    timestamp: Optional[str] = Field(None, description="Error timestamp (ISO8601)")
    error_signature: Optional[str] = Field(None, description="Error message/signature")
    stack_trace: Optional[str] = Field(None, description="Stack trace if available")
    version_sha: Optional[str] = Field(None, description="Git SHA or version")
    metric_anomalies: List[Dict[str, Any]] = Field(default_factory=list)
    
    blockers: List[str] = Field(default_factory=list, description="Issues preventing analysis")
    recommendations: List[str] = Field(default_factory=list, description="Next steps")
    pending_steps: List[str] = Field(default_factory=list, description="Steps remaining for interactive mode")
    
    @validator('status')
    def validate_status(cls, v):
        allowed = ['SUCCESS', 'PARTIAL', 'FAILURE', 'WAITING_FOR_APPROVAL']
        if v not in allowed:
            raise ValueError(f"Status must be one of {allowed}")
        return v
    
    def is_valid_evidence(self) -> bool:
        """Check if evidence is sufficient for next phase"""
        return self.status == "SUCCESS" and self.error_signature is not None


class RootCause(BaseModel):
    """Root cause details from Investigator"""
    file: str
    line: int
    function: str
    defect_type: str = Field(..., description="null_check|timeout|race_condition|logic_error|config_error")
    evidence: str = Field(..., description="Code snippet showing the issue")


class InvestigatorOutput(BaseModel):
    """Expected output schema from Investigator Agent"""
    status: str = Field(..., description="ROOT_CAUSE_FOUND|HYPOTHESIS|INSUFFICIENT_DATA")
    confidence: Optional[float] = Field(0.0, ge=0.0, le=1.0)
    
    root_cause: Optional[RootCause] = None
    dependency_chain: List[str] = Field(default_factory=list, description="Call stack")
    hypothesis: Optional[str] = Field(None, description="If root cause not definitive")
    
    blockers: List[str] = Field(default_factory=list)
    recommendations: List[str] = Field(default_factory=list)
    
    @validator('status')
    def validate_status(cls, v):
        allowed = ['ROOT_CAUSE_FOUND', 'HYPOTHESIS', 'INSUFFICIENT_DATA']
        if v not in allowed:
            raise ValueError(f"Status must be one of {allowed}")
        return v
    
    def is_valid_evidence(self) -> bool:
        """Check if we have actionable findings"""
        conf = self.confidence if self.confidence is not None else 0.0
        return self.status in ["ROOT_CAUSE_FOUND", "HYPOTHESIS"] and conf >= 0.3


class ArchitectOutput(BaseModel):
    """Expected output schema from Architect Agent"""
    status: str = Field(..., description="SUCCESS|PARTIAL|FAILURE")
    confidence: Optional[float] = Field(0.0, ge=0.0, le=1.0)
    
    rca_content: Any = Field(..., description="Full RCA content (JSON or Markdown)")
    rca_url: Optional[str] = Field(None, description="GCS URL to RCA document")
    
    limitations: List[str] = Field(default_factory=list, description="Known gaps in analysis")
    recommendations: List[str] = Field(default_factory=list)
    
    @validator('status')
    def validate_status(cls, v):
        allowed = ['SUCCESS', 'PARTIAL', 'FAILURE']
        if v not in allowed:
            raise ValueError(f"Status must be one of {allowed}")
        return v


class SequentialThinkingPlan(BaseModel):
    """Plan generated by Sequential Thinking specialist"""
    plan_id: str
    reasoning: str = Field(..., description="Why this plan was chosen")
    
    steps: List[Dict[str, Any]] = Field(..., description="Ordered investigation steps")
    
    def get_next_step(self, completed_steps: List[str]) -> Optional[Dict[str, Any]]:
        """Get the next step to execute"""
        for step in self.steps:
            step_id = step.get('step_id')
            if step_id not in completed_steps:
                return step
        return None
